[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
serde = { version = "1.0", features = ["derive"] }
secp256k1={version = "0.29",features = ["recovery"]}
sha2 = "0.10"
sha3 = "0.10"
hex = "0.4.3"
rand= "0.8.5"